### ISSUE TITLE
OverflowException in ItemService

### ISSUE THREAD

**Issue by TuononenP** [podio/podio-dotnet#49]
I am trying to use Podio C# SDK to get Podio app item data. For most apps it works, but for one app it throws an error.

This is the C# method I am calling:
PodioCollection<Item> items = Podio.ItemService.FilterItems(appId, 500, fetchedItemsCount, filter);
where app id is integer value of app's id, fetchedItemsCount is 0, filter is null.

This is the exception that throws:

```
at Newtonsoft.Json.Utilities.ConvertUtils.Int32Parse(Char[] chars, Int32 start, Int32 length)
at Newtonsoft.Json.JsonTextReader.ParseNumber()
at Newtonsoft.Json.JsonTextReader.ParseValue()
at Newtonsoft.Json.JsonReader.ReadAsInt32Internal()
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonConverter[] converters)
at PodioAPI.Utils.JSONSerializer.Deserilaize[T](String json)
at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
at PodioAPI.Podio.Request[T](RequestMethod requestMethod, String url, Object requestData, Object options)
at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
at PodioAPI.Podio.Post[T](String url, Object requestData, Object options)
at PodioAPI.Services.ItemService.FilterItems(Int32 appId, FilterOptions filterOptions, Boolean includeFiles)
at PodioAPI.Services.ItemService.FilterItems(Int32 appId, Nullable`1 limit, Nullable`1 offset, Object filters, Nullable`1 remember, String sortBy, Nullable`1 sortDesc, Boolean includeFiles)

```
As far as I can see Newtonsoft library inside Podio SDK is having problems parsing some Integer value.

![podio sdk - arithmetic overflow](https://user-images.githubusercontent.com/47377/38808414-ca7fb3d0-4188-11e8-9c3e-a9587d31d916.png)

**Comment by TuononenP** [comment]
Ping. Is it possible that somehow somebody has written alphabets in integer column in Podio? Do you have any checks to prevent this? It could theoretically cause this issue if Podio does not have type checking.

**Comment by PavloBasiuk** [comment]
Hi @TuononenP 

There is no way that Podio has alphabets in integer column, but it could be that column is not `integer` but `long int` and that could cause similar error. Are you sure you are using latest code? 
There were similar errors reported in https://github.com/podio/podio-dotnet/issues/48 and https://github.com/podio/podio-dotnet/issues/46. And it was fixed in https://github.com/podio/podio-dotnet/pull/47

**Comment by TuononenP** [comment]
I am still getting this exception in multiple apps. I cannot figure out the reason and as far as I know there is not anything I can do because the exception happens in NewtonSoft code inside Podio library. I even checked the field types of apps and cannot we have apps that work with category, date, app, text, number fields and apps that won't so I didn't find a reason from the fields. Also checked content of rows and there wasn't anything special either. Then I tried Python library which worked retrieving those apps. This is really a major problem for our client. It would be quite a bit task to code a lot of things again with Python but If Podio team does not bother to fix this I don't think I have any other option.

**Comment by TuononenP** [comment]
Version is 1.5.8.

**Comment by PavloBasiuk** [comment]
Ok, that version is supposed to have needed fix for `int` to `long` change. Then it might be some similar but different issue. Can you find item that Podio SDK fail to fetch and investigate that item's properties and fields?

**Comment by TuononenP** [comment]
Ok, I will try that on Friday. This problem happens with multiple workspace apps that contain about 1000 items, but I will loop them through one by one after I find out a way how to fetch all item ids for an app.
